name: Dummy Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  dummy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run dummy status check
        run: echo "This is a dummy status check"
